
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build docker images
      script:
      - docker build -t egifedcloud/cloudkeeper cloudkeeper/core
      - docker build -t egifedcloud/cloudkeeper-os cloudkeeper/os
      - docker build -t egifedcloud/bdii cloud-info/bdii
      - docker build -t egifedcloud/sitebdii cloud-info/site
      - docker build -t egifedcloud/cloudbdii cloud-info/cloud
      - docker build -t egifedcloud/caso accounting/caso
      - docker build -t egifedcloud/ssm accounting/ssm
