sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else echo
      "latest"; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t cloudkeeper cloudkeeper/core
    - docker tag cloudkeeper $DOCKER_REPO/cloudkeeper:$TAG
    - docker build -t cloudkeeper-os cloudkeeper/os
    - docker tag cloudkeeper-os $DOCKER_REPO/cloudkeeper-os:$TAG
    - docker build -t bdii cloud-info/bdii
    - docker tag bdii $DOCKER_REPO/bdii:$TAG
    - docker build -t sitebdii cloud-info/site
    - docker tag sitebdii $DOCKER_REPO/sitebdii:$TAG
    - docker build -t cloudbdii cloud-info/cloud
    - docker tag cloudbdii $DOCKER_REPO/cloudbdii:$TAG
    - docker build -t caso accounting/caso
    - docker tag caso $DOCKER_REPO/caso:$TAG
    - docker build -t ssm accounting/ssm
    - docker tag ssm $DOCKER_REPO/ssm:$TAG
    after_success:
    - docker push $DOCKER_REPO/cloudkeeper
    - docker push $DOCKER_REPO/cloudkeeper-os
    - docker push $DOCKER_REPO/bdii
    - docker push $DOCKER_REPO/sitebdii
    - docker push $DOCKER_REPO/cloudbdii
    - docker push $DOCKER_REPO/caso
    - docker push $DOCKER_REPO/ssm
env:
  global:
  - DOCKER_REPO=egifedcloud
  - secure: RTH6pB5W8kKjkAYRyQVNcAx7wO1dLJrZsrzXnQc162HGl2T6Vo5Kw9uHyqa5PSPE4MspG0X817pFUGTKPT4DS6uE7y6PwIOr8/pqxcYBXVPCVz1GrwLxysyzrMqJwWIRnRqpkqjHqoe2zfeqCxlmhiZ6acrb7KzK4GnC+0c9whAo/MtrwF8nirbIhDtpaxZvZvBzA/JCleTkyCDkRoB3raM5VGD0qKr9d5AFDpvXJwKA/y9fmanpBB2N40VI/8qI1jE0L7BUHmimpLzmzv4UZUkTQtNYKFBi43mSr5IUGT7bcUvv0McjWb+5howUP8bMHM7OfGB+ARaG37uhpGIr6v7oeIsbj56o/c8yIXb7Y87LEmEnAk0SD85gUeAQSGXIBUZHQNGdEQGkJ9xOkuf+kbv5MatABsXqdVSzPwwXoeLD/z1VUPHbvwf00iR5Mu63MR9WK0F/DI8lmrFtbJelQ4MEGlai5kWNlNVBPgYv8oLdPF2FyIL7oHCQBUfkCWjXWZ2QK/SuCROgXkUy4tD/3r0Q02PooTe2l8mOqyVPgTb62+t6k7aEo8esZIlQJrqgNFKGEOHlADcgQ1DlumQj8x/eh0FJ5rC+S43OcAKo9cHo/2jE8AdA2SS/zSkCquhCqDHto4sV6ARp+gXGWlNgjecXdRbI0bx7K1/QQjYJwyA=
  - secure: HA1VvLrmZSStscVT7Iql+O7n4eh686udGp1KfadoPsFXx2EfGOcrCA6xUOefRZpqRe+nIjiE6cxFWdyTplATr+cpICYNS2omNlJXVlsU45w9c60wBBQj21TmvPguQyDWeOWdyhcCq5boCkLepoKwMultIznnFhnrz5jsoees0X25rVM8sw/M6qg5Z0gwgDibUUHZopBXYLovefZ3mXj7AfuPyH0Dn3KnpQ/yXl1GetJeYOCSLtTQbpV3Jnh5BqkAJ39lhYfiGSiCyGyxNfT7fB8rm4byj0G/QPuwnpWH2FZRRUM0gnNcDAAKSsEYg/Y0xIoz/Cbs/uo0E5/YpFlwdOY6iYDIG4E8LdN6BBXY9aEf7YGhpwnxug7yfheIT36o1JspxZ4r+XcSr+VypD8ONha+0c7jUIb64dekQX1qRCLRY8lMNi80o6sr2jFZuo/KEG+2PRMGCNp5WG+93FiSeRRenGXkPZ8euosSAV3Vmhs5Q/kwvGfp35qVNCe2XpImSLx4XcyaIGPf6sVKYnJBYLp/IRzROfjCqgoi+s4Gd3S3LXKyY9trPKRIeXdx7Z9XQhSkLpzQj+QnPKNKAfWpzbnr88jC5W8IoZfAQ7BNksRLHaNHfcsI1bziBExgVZiTgbv1vLiyH5OGth5+c5KXU4C7+fHSe4XUFWUPjD9Am8g=
