sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else echo
      "latest"; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t cloudkeeper cloudkeeper/core
    - docker tag cloudkeeper $DOCKER_REPO/cloudkeeper:$TAG
    - docker build -t cloudkeeper-os cloudkeeper/os
    - docker tag cloudkeeper-os $DOCKER_REPO/cloudkeeper-os:$TAG
    - docker build -t bdii cloud-info/bdii
    - docker tag bdii $DOCKER_REPO/bdii:$TAG
    - docker build -t sitebdii cloud-info/site
    - docker tag sitebdii $DOCKER_REPO/sitebdii:$TAG
    - docker build -t cloudbdii cloud-info/cloud
    - docker tag cloudbdii $DOCKER_REPO/cloudbdii:$TAG
    - docker build -t caso accounting/caso
    - docker tag caso $DOCKER_REPO/caso:$TAG
    after_success:
    - docker push $DOCKER_REPO/cloudkeeper
    - docker push $DOCKER_REPO/cloudkeeper-os
    - docker push $DOCKER_REPO/bdii
    - docker push $DOCKER_REPO/sitebdii
    - docker push $DOCKER_REPO/cloudbdii
    - docker push $DOCKER_REPO/caso
env:
  global:
  - DOCKER_REPO=egifedcloud
  - secure: EhyP1qxuiBk+bueSF0OAr1mBFlP4nD7JYgDnO0bVQkScCAESU1GpAMxHNjfmN9qtuN0honZ7KH3g+W+ZkSEc2+cwJ+IiJwVlZeJEObluGaEf0kYc9w+2jrXrSHGRiZUnCwu1eOibVhc34ygTOUlp2ho9idLTVbxvnD25aQb+dOJugZv2Pzjd8O0Oc/pbVxL0wV/h0Cfo9AJxkvAvfg/eAhXEY1pz395KGlKytT6TPrzCDERPsf2UiIdBsG3lAdmbzVqv4xNnRYAS0YQ13ku+/m0b9XzNIS7siTJ/2a+ErloSRSJEOflKZwIoKFDU9ZIHi2kMotm8MsdKHLHpH06+kmgPjBXxiHfmE5SAT+4IaWaWz2cbxLc/M/mGO6XjFHq2R+FTTqXoZvYI2agyrkhxLVaaivTJaOoKrZ/EqL0s67cCN+8+I8cafR9cSUbpCeitDBOZZbSCgtoj//zCOB1bTd2V+Xm4nubesIlWQ4+uZYrVyW9/kYW90eT89Rk380i7KRR7WGypyAkwGLkQr3QfeKaUgAGwdXx8cT9due2C8/pvEH35snR6iwPYHwIj7JDdTL8eCec/vVkCS0HX+FvNWn2RSWTTOknfyzKcWvkr1tBart/rW9jdfabz5flChapc619Z0aztfNbff/euqKCYZ5xvtND2tnR6/N+MzSVkZPM=
  - secure: efbZFZ1w6B1NmZbRZgThZe/jzJxW2ohmKKxPZ5qAsqLGdCHtBB/V0Ek4REOMsJpbKBWShpFuqYl4VQUTN1O5KBt60g5x/AGk4TfNpnNEslSMSiBwGzV7WvF+kHnVA039jvAo5hUm4+JNbpjDTGaiS7KxdW6Q8dHViWAN1k3W+NUUS6Fe/O+YIAACYIhdNiLk8VHQUPqS278b8KXNH2bxobbSBamIjQUTPfb1OXbMHhSBVfXZ8efi2IDIhfMVt6Aqf7UEFj2KazUOtF2iq0LHy7hXEmSFsU9H8r3DxMkU87xAp2BW+OF+8UTGHXSQvOYL25LkaaojNRCFCS4X45YM0d1BIy+EOzou648qIiZW84ou7FyOD1FfBts2wuBv02c7iSiDKtkhdTHTOdLrMNJTD2sfLoheILL9SzRV2wzw8O5WspzA5gaPIyVyjJppCkS0ifnAdbfoWelK1ZHyVshvXwReO6jWpDXu6UJGj04evirFsB6H6DMlt+2jnKL2SmiyPPUHpLOQiTwSyqqzlSuVKYKM1mZaAmLLic8C43Y1YAQZtYv/nrIp3C0OMaxAoUAeqVkI780JxlUR36aCKrxfYMLPAiKB2+m5fycjTX9eAAtSQjrlu4qWw4L3Vianu8W9xet3OTtriROfdVbk3IUrv4hGvgiNZclIHMK/wlo5PvM=
