
sudo: required

services:
  - docker

jobs:
  include:
    - stage: build docker images
      script:
      - pushd accounting/caso && docker build -t egifedcloud/caso . && popd
      - pushd accounting/ssm && docker build -t egifedcloud/ssm . && popd
